import about from './about_me.png';
import full_stack from './full_stack.png';
import c_sharp from './c-sharp.png';
import c_plus_plus from './c++.png';
import mongoDB from './mongodb.svg';
import python from './python.png';
import react from './react.png';
import figma from './figma.png';
import google_map from './google-maps.png';
import sql from './database.png';
import php from './php.png';
import three_dimension from './3d.png';
import django from './django.png';
import nodeJS from './nodejs.png';
import UF from './UF.png';
import aquinas from './aquinas.jpg';

export const aboutImage = about;
export const fullStackImage = full_stack;
export const cSharpImage = c_sharp;
export const cPlusPlusImage = c_plus_plus;
export const mongoDBImage = mongoDB;
export const pythonImage = python;
export const reactImage = react;
export const figmaImage = figma;
export const googleMapImage = google_map;
export const sqlImage = sql;
export const phpImage = php;
export const threeDJSImage = three_dimension;
export const djangoImage = django;
export const nodeJSImage = nodeJS;
export const UFImage = UF;
export const aquinasImage = aquinas;
