export const techStack = {
  js: 'javascript',
  python: 'python',
  mongoDB: 'mongoDB',
  react: 'react',
  fastAPI: 'fastAPI',
  dJango: 'dJango',
  cSharp: 'c#',
  cPlusPlus: 'c++',
  figma: 'figma',
  googleMap: 'googleMap',
  sql: 'sql',
  php: 'php',
  threeDJS: '3d.js',
  nodeJS: 'nodeJS',
  wechat: 'wechat',
};
