export const techStack = {
  js: 'javascript',
  python: 'python',
  mongoDB: 'mongoDB',
  react: 'react',
  fastAPI: 'fastAPI',
  dJango: 'dJango',
  cSharp: 'c#',
  unity: 'unity',
  cPlusPlus: 'c++',
  figma: 'figma',
  googleMap: 'googleMap',
  sql: 'sql',
  php: 'php',
  threeDJS: '3d.js',
  nodeJS: 'nodeJS',
  wechat: 'wechat',
  openAI: 'openAI',
  go: 'go',
  gcp: 'gcp',
  lambda: 'lambda',
  aws: 'aws',
  hardware: 'hardware',
  ai: 'ai',
};
